#!/usr/bin/env node
// Synced from obsidian-boiler-template/tooling/shared/release.mjs. Do not edit this file directly.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';

const RELEASE_LEVELS = new Set(['patch', 'minor', 'major']);

function getPnpmCommand() {
  return process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm';
}

function run(command, args) {
  const result = spawnSync(command, args, { stdio: 'inherit' });
  if (result.error) {
    console.error(`Failed to run ${command}: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    process.exit(result.status ?? 1);
  }
}

function runWithEnv(command, args, env) {
  const result = spawnSync(command, args, {
    stdio: 'inherit',
    env: { ...process.env, ...env },
  });
  if (result.error) {
    console.error(`Failed to run ${command}: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    process.exit(result.status ?? 1);
  }
}

function readPackageVersion() {
  return JSON.parse(fs.readFileSync('package.json', 'utf8')).version;
}

function normalizeManifest() {
  if (!fs.existsSync('manifest.json')) {
    return;
  }
  const raw = fs.readFileSync('manifest.json', 'utf8');
  const normalized = `${JSON.stringify(JSON.parse(raw), null, '\t')}\n`;
  if (raw !== normalized) {
    fs.writeFileSync('manifest.json', normalized);
  }
}

function requireCleanWorktree() {
  const result = spawnSync('git', ['status', '--short'], { encoding: 'utf8' });
  if (result.error) {
    console.error(`Failed to check git status: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    process.exit(result.status ?? 1);
  }
  if (result.stdout.trim().length > 0) {
    console.error('Release requires a clean git worktree.');
    process.exit(1);
  }
}

const level = process.argv[2];
if (!RELEASE_LEVELS.has(level)) {
  console.error(`Usage: node scripts/release.mjs <patch|minor|major>`);
  process.exit(1);
}

const pnpm = getPnpmCommand();
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
requireCleanWorktree();
if (pkg.scripts?.['sync:check']) {
  run(pnpm, ['sync:check']);
}
run(pnpm, ['run', 'ci']);
normalizeManifest();
requireCleanWorktree();
run(pnpm, ['version', level, '--no-git-tag-version', '--ignore-scripts']);
const version = readPackageVersion();
runWithEnv('node', ['scripts/version.mjs'], { npm_package_version: version });
run('git', ['add', 'package.json', 'manifest.json', 'versions.json']);
run('git', ['commit', '-m', `chore(release): ${version}`]);
run('git', ['tag', '-a', version, '-m', `chore(release): ${version}`]);
run('git', ['push']);
run('git', ['push', '--tags']);
